# Configuration for Meshtastic Network Monitor

# List of Node IDs to prioritize for active testing (Traceroute, etc.)
# Format: "!<NodeID>"
priority_nodes:
  # - "!12345678" 
   - "!d75ae2a0"

# Logging Level [warn|info|debug]
log_level: info

# Auto-Discovery Settings (Used if priority_nodes is empty)
# Roles to prioritize for auto-discovery
auto_discovery_roles:
  - ROUTER
  - ROUTER_LATE
  - REPEATER
  - CLIENT

# Limit number of auto-discovered nodes
auto_discovery_limit: 5

# Reporting Settings
# Generate report after N full testing cycles
report_cycles: 1
